# Generated by Django 5.1.1 on 2024-09-29 15:41

from django.db import migrations, models

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='User ID')),
                ('email', models.EmailField(max_length=100, unique=True)),  # Adjusted max_length
                ('first_name', models.CharField(max_length=50)),
                ('surname', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('password', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('customer', 'Customer'), ('administrator', 'Administrator')], max_length=15)),  # Keep as CharField
            ],
            options={
                'db_table': 'Users',  # Make sure this matches your database table name
            },
        ),
    ]
