# Generated by Django 5.1.1 on 2024-11-28 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_user_last_login_alter_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('product_type', models.CharField(choices=[('motorcycle', 'Motorcycle'), ('part', 'Part')], max_length=50, null=True)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('stock_quantity', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'Products',
            },
        ),
    ]
