# Generated by Django 5.1.1 on 2024-11-28 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_type',
            field=models.CharField(choices=[('motorcycle', 'Motorcycle'), ('part', 'Part')], default='motorcycle', max_length=50),
        ),
    ]
