# Generated by Django 5.1.1 on 2024-12-02 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_products_product_type'),
    ]

    operations = [
    ]
