# Generated by Django 5.1.1 on 2024-12-03 16:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20241202_1119'),
    ]

    operations = [  
    ]
